name: mcs
description: A new Flutter project.



publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  pin_code_fields: ^7.3.0
  carousel_slider: ^4.0.0
  readmore: ^2.1.0
  fluttertoast: ^8.0.8
  image_picker: ^0.8.4+3
  dio: ^4.0.1
  cached_network_image: ^3.1.0+1
  razorpay_flutter: ^1.2.9
  logger: any
  json_annotation: ^4.5.0
  shared_preferences: ^2.0.12
  synchronized:
  pretty_dio_logger: ^1.2.0-beta-1
  retrofit: ^3.0.1
  google_fonts: ^3.0.1
  auto_size_text: ^3.0.0
  flutter_screenutil: ^5.1.0
  intl: ^0.17.0
  date_picker_timeline: ^1.2.3
  flutter_rating_bar: ^4.0.0
  flutter_dotenv: ^5.0.2
  share: ^2.0.4
  firebase_core: ^1.11.0
  firebase_messaging: ^11.2.5
  flutter_bloc: ^8.0.1
  bloc: ^8.0.2
  equatable: ^2.0.3
  pinput: ^2.2.9
  sms_autofill: ^2.1.2
  permission_handler: ^9.2.0
  badges: ^2.0.2
  freezed_annotation: ^2.0.3
  shimmer: ^2.0.0
  animate_do: ^2.1.0

  




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  analyzer: any
  build_runner: any
  json_serializable: ^6.1.1
  retrofit_generator: ^4.0.1
  source_gen: ^1.2.2
  freezed: ^2.0.3+1
  

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/jsons/
    - .env

